# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [33]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
from pprint import pprint

# Import API key
from api_keys import g_key
# Configure gmaps
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csvfile = 'Weather_DF.csv'
weather_df = pd.read_csv(csvfile)
weather_df.head(20)

,Unnamed: 0,City,Lat,Long,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Aklavik,68.22,-135.01,50.00,76,75,8.05,CA,2020-07-11 02:24:06
1,1,Yellowknife,62.46,-114.35,70.00,52,20,6.93,CA,2020-07-11 02:28:54
2,2,Constitución,-35.33,-72.42,49.37,78,80,6.13,CL,2020-07-11 02:28:54
3,3,Jamestown,42.10,-79.24,72.00,88,90,3.36,US,2020-07-11 02:26:41
4,4,Marsh Harbour,26.54,-77.06,84.65,75,100,13.80,BS,2020-07-11 02:25:38
5,5,Mahébourg,-20.41,57.70,68.00,68,40,17.22,MU,2020-07-11 02:24:28
6,6,Castro,-24.79,-50.01,51.55,89,0,4.07,BR,2020-07-11 02:28:55
7,7,Eyl,7.98,49.82,80.46,62,13,28.70,SO,2020-07-11 02:28:55
8,8,Qinzhou,21.95,108.62,89.80,67,100,22.44,CN,2020-07-11 02:28:55
9,9,Hammerfest,70.66,23.68,46.40,93,75,16.11,NO,2020-07-11 02:28:55
10,10,Puerto Ayora,-0.74,-90.35,66.99,95,100,7.78,EC,2020-07-11 02:28:56
11,11,Port Elizabeth,-33.92,25.57,60.80,44,100,10.29,ZA,2020-07-11 02:25:48
12,12,Punta Arenas,-53.15,-70.92,30.20,92,98,9.17,CL,2020-07-11 02:28:56
13,13,Ilulissat,69.22,-51.10,42.80,81,100,8.05,GL,2020-07-11 02:28:56
14,14,Shirokiy,49.76,129.52,74.93,72,0,6.69,RU,2020-07-11 02:28:56
15,15,São Sebastião,-23.76,-45.41,65.84,80,93,8.97,BR,2020-07-11 02:28:56
16,16,Ambulu,-8.35,113.61,79.45,73,52,2.30,ID,2020-07-11 02:28:56
17,17,Udalguri,26.77,92.13,77.27,93,100,11.54,IN,2020-07-11 02:28:57
18,18,Mitsamiouli,-11.38,43.28,76.48,68,0,12.03,KM,2020-07-11 02:28:57
19,19,Hithadhoo,-0.60,73.08,83.57,73,97,7.74,MV,2020-07-11 02:28:57

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key = g_key)

In [48]:
latlonglocations = weather_df[["Lat", "Long"]]
weight = weather_df["Humidity"].astype(float)
figure_layout = {
    'width': '900px',
    'height': '500px',
    'border': '2px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

# Create heat layer
heat_layer = gmaps.heatmap_layer(latlonglocations, weights=weight, 
                                 dissipating=False, max_intensity = 100,
                                 point_radius=2)
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(border='2px solid black', height='500px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
#My weather conditions: Max Temp </= 80, windspeed < 10, < 60 cloudiness, humidity < 40
# I am going to do a .loc with conjunctions to find my desired cities.
myweather_df = weather_df.loc[(weather_df['Max Temp'] <= 80)\
                              & (weather_df['Wind Speed'] <= 7)\
                              & (weather_df['Cloudiness'] < 50)\
                             & (weather_df['Humidity']< 35)]
# Drop null/NA values and display DF
myweather_df.dropna()
myweather_df = myweather_df.drop(columns=['Unnamed: 0'])
myweather_df

,City,Lat,Long,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
80,Korla,41.76,86.15,79.72,30,47,3.60,CN,2020-07-11 02:29:04
225,Ust-Nera,64.57,143.20,71.76,24,11,3.20,RU,2020-07-11 02:27:52
232,Kaeo,-35.10,173.78,62.01,6,7,1.99,NZ,2020-07-11 02:29:22
587,Baraki Barak,33.97,68.95,71.91,22,0,5.30,AF,2020-07-11 02:30:02

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
#hotel_df = myweather_df.insert(["Hotel Name"])
hotel_df = myweather_df.loc[:,["City","Country", "Lat", "Long"]]
hotel_df['Hotel Name']=""
hotel_df['Hotel Lat']=""
hotel_df['Hotel Lng']=""
hotel_df

             City Country    Lat    Long Hotel Name Hotel Lat Hotel Lng
80          Korla      CN  41.76   86.15
225      Ust-Nera      RU  64.57  143.20
232          Kaeo      NZ -35.10  173.78
587  Baraki Barak      AF  33.97   68.95

In [7]:
# Set up Parameter variables
target_search = "hotel"
target_radius = 5000
target_type = "lodging"
# set up a Parameters dictionary
params = {"keyword": target_search,"radius": target_radius,"type": target_type,"key": g_key}
# Base URL
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
response = requests.get(base_url, params=params).json()

In [8]:
# find the closest hotel of each type to coordinates
# use iterrows to iterate through pandas dataframe
#latlist = []
#longlist = []

print('''
---------------------
Beginning your search
---------------------
''')
for index, row in hotel_df.iterrows():
    # Retrieve hotels but I have to go by the lat and long
    lat = row["Lat"]
    long = row["Long"]
    name = row["City"]
    # add keyword to params dict
    params["location"] = (f"{lat},{long}")
    # assemble url and make API request
    print(f"Retrieving Results for {name}.")
    response = requests.get(base_url, params=params).json()
    # extract results
    results = response['results']
    try:
        print(f"The closest hotel to {name} is {results[0]['name']}")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
        hotel_df.loc[index, "Hotel Lat"] = results[0]['geometry']['location']['lat']
        hotel_df.loc[index, "Hotel Lng"] = results[0]['geometry']['location']['lng']
        
    except(KeyError, IndexError):
        print(f"Could not find a hotel for {name}... skipping to next vacation spot.")
        hotel_df.loc[index, "Hotel Name"] = "Not Found"
        hotel_df.loc[index, "Hotel Lat"] = hotel_df.loc[index, "Lat"]
        hotel_df.loc[index, "Hotel Lng"] = hotel_df.loc[index, "Long"]
    print("------------")
    
print('''
------------------------
The search has concluded
------------------------
''')

---------------------
Beginning your search
---------------------

Retrieving Results for Korla.
The closest hotel to Korla is The Garden Hotel Korla
------------
Retrieving Results for Ust-Nera.
The closest hotel to Ust-Nera is Gostevoy Dom
------------
Retrieving Results for Kaeo.
The closest hotel to Kaeo is Pacific Harbour Lodge
------------
Retrieving Results for Baraki Barak.
Could not find a hotel for Baraki Barak... skipping to next vacation spot.
------------

------------------------
The search has concluded
------------------------

In [9]:
hotel_df['Hotel Lat'] = hotel_df['Hotel Lat'].astype(float)
hotel_df['Hotel Lng'] = hotel_df['Hotel Lng'].astype(float)
hotel_df

,City,Country,Lat,Long,Hotel Name,Hotel Lat,Hotel Lng
80,Korla,CN,41.76,86.15,The Garden Hotel Korla,41.759487,86.153250
225,Ust-Nera,RU,64.57,143.20,Gostevoy Dom,64.562463,143.239043
232,Kaeo,NZ,-35.10,173.78,Pacific Harbour Lodge,-35.054260,173.740702
587,Baraki Barak,AF,33.97,68.95,Not Found,33.970000,68.950000

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Hotel Lat", "Hotel Lng"]]

In [43]:
figure_layout = {
    'width': '900px',
    'height': '500px',
    'border': '2px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
#fig(layout=FigureLayout(height='420px'))
heat_layer = gmaps.heatmap_layer(latlonglocations, weights=weight, 
                                 dissipating=False, max_intensity = 100,
                                 point_radius=1)
gmaps.figure(layout=figure_layout)
fig.add_layer(markers)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(border='2px solid black', height='500px', margin='0 auto 0 auto', padding='1px', wi…